# These are supported funding model platforms

github: [kavehtehrani]
buy_me_a_coffee: kavehtehrani
custom: [https://www.blockchain.com/explorer/search?search=bc1quude6cv8dr78g2ad0k25tr5mzy3cdkcuyhcryf]
